const selectors = require('../supporting/selectors')
const data = require('../supporting/data')

module.exports = {
appRunThrough : (browser, test) => {
    browser
        .waitForElementVisible(selectors.buttons.getStarted, 2000)
        .click(selectors.buttons.getStarted)
        .waitForElementVisible(selectors.buttons.nextButton, 2000)
        .click(`${selectors.fields.loanTypes} ${selectors.loanTypes[test.loanTypes]}`)
        .click(`${selectors.fields.propertyTypes} ${selectors.propertyTypes[test.propertyTypes]}`)
        .click(selectors.buttons.nextButton)
        .waitForElementVisible(selectors.fields.cityName, 2000)
        .setValue(selectors.fields.cityName, test.cityName)
        .click(selectors.buttons.nextButton)
        .waitForElementVisible(selectors.propertyPurpose.primaryHome, 2000)
        .click(selectors.propertyPurpose[test.propertyPurpose])
        .waitForElementVisible(selectors.buttons.yesButton, 2000)
        .click(selectors.buttons[test.foundHome])
        .waitForElementVisible(selectors.buttons.noButton, 2000)
        .click(selectors.buttons[test.foundAgent])
        .waitForElementVisible(selectors.fields.downPayment, 2000)
        .setValue(selectors.fields.purchasePrice, test.purchasePrice)
        .setValue(selectors.fields.downPayment, test.downPayment)
        .click(selectors.buttons.nextButton)
        .waitForElementVisible(selectors.creditScore.excellentCredit, 2000)
        .click(selectors.creditScore[test.creditScore])
        .waitForElementVisible(selectors.bankruptcyForeclosure.neither, 2000)
        .click(selectors.bankruptcyForeclosure[test.bankruptcyForeclosure])
        .waitForElementVisible(selectors.fields.addressOne, 2000)
        .setValue(selectors.fields.addressOne, test.addressOne)
        .setValue(selectors.fields.addressTwo, test.addressTwo)
        .setValue(selectors.fields.addressThree, test.addressThree)
        .click(selectors.buttons.nextButton)
        .waitForElementVisible(selectors.fields.firstName, 2000)
        .setValue(selectors.fields.firstName, test.firstName)
        .setValue(selectors.fields.lastName, test.lastName)
        .setValue(selectors.fields.email, test.email)
        .click(selectors.buttons.nextButton)
        .expect.element(selectors.result.nameResult).text.to.contain(test.firstName)
        browser.expect.element(selectors.result.nameResult).text.to.contain(test.lastName)
        browser.expect.element(selectors.result.emailResult).text.to.equal(test.email)
        browser.expect.element(selectors.result.cityResult).text.to.contain(test.cityName)
        browser.expect.element(selectors.result.homePriceResult).text.to.contain(test.purchasePrice)
        browser.expect.element(selectors.result.downPaymentResult).text.to.contain(test.downPayment)

}
}